/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SecureFederatedDatabase__factory } from "./SecureFederatedDatabase__factory";
export { UniversalAdapter__factory } from "./UniversalAdapter__factory";
