/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SecureFederatedDatabase } from "./SecureFederatedDatabase";
export type { UniversalAdapter } from "./UniversalAdapter";
